version: '2'

services:

  frontend_builder:
    build: frontend
    volumes:
     - './frontend/dist:/frontend/dist'
    command: npm run build

  website:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - './isserviceup:/isserviceup/isserviceup'
     - './frontend/dist:/isserviceup/static'
    depends_on:
     - frontend_builder
    command: gunicorn -c "isserviceup/config/gunicorn.py" isserviceup.app:app --reload

  redis:
    image: redis
    command: redis-server --requirepass devpassword --appendonly yes
    volumes:
     - 'redis:/data'

  celery_beat:
    build: .
    command: celery -A isserviceup.celeryapp.app beat
    volumes:
     - './isserviceup:/isserviceup/isserviceup'
    depends_on:
     - redis

  celery:
    build: .
    command: celery worker -l info -P gevent -c 50 -A isserviceup.celeryapp.app
    volumes:
     - './isserviceup:/isserviceup/isserviceup'
    depends_on:
     - redis

volumes:
  redis:
