version: '2'

services:
  website:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - '.:/isserviceup'
    command: gunicorn -c "isserviceup/config/gunicorn.py" isserviceup.app:app --reload

  redis:
    image: redis
    command: redis-server --requirepass devpassword --appendonly yes
    volumes:
     - 'redis:/data'

  celery_beat:
    build: .
    command: celery -A isserviceup.celeryapp.app beat
    volumes:
      - '.:/isserviceup'

  celery:
    build: .
    command: celery worker -l info -P gevent -c 50 -A isserviceup.celeryapp.app
    volumes:
      - '.:/isserviceup'

volumes:
  redis: